version: '2'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.5.7'
    ports:
      - '2181:2181'
    volumes:
      - './zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:2.5.0'
    container_name: kafka
    ports:
      - '9092:9092'
    volumes:
      - './kafka_data:/bitnami'
      - './kafka_log:/tmp/kafka_mounts/logs'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LOG_DIRS=/tmp/kafka_mounts/logs
    depends_on:
      - zookeeper
  # kafka-connect:
  #   image: 'bitnami/kafka:2.5.0'
  #   container_name: kafka_connect
  #   ports:
  #     - '8083:8083'
  #   volumes:
  #     - './kafka_connect_data:/bitnami'
  #     - './kafka_connect_config/connect-distributed.properties:/opt/bitnami/kafka/config/connect-distributed.properties'
  #   depends_on:
  #     - zookeeper
  #     - kafka
  #   command: /opt/bitnami/kafka/bin/connect-distributed.sh /opt/bitnami/kafka/config/connect-distributed.properties